[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' maxcdn.bootstrapcdn.com; style-src fonts.googleapis.com 'self' maxcdn.bootstrapcdn.com 'unsafe-inline'; font-src fonts.gstatic.com 'self'"