[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self'; style-src fonts.googleapis.com fonts.gstatic.com 'self' https://maxcdn.bootstrapcdn.com 'unsafe-inline'"